framework:
    messenger:
        reset_on_message: true
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }
        default_bus: messenger.bus.events
        buses:
            messenger.bus.events:
                middleware:
                    - validation
        transports:
            events:
                dsn: '%env(resolve:MESSENGER_EVENTS_DSN)%'
                options:
                    exchange:
                        type: topic
                    queues:
                        callcenter.events:
                            binding_keys:
        routing:
